//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISessionService", CallbackContract=typeof(ISessionServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface ISessionService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/IniciarSesion", ReplyAction="http://tempuri.org/ISessionService/IniciarSesionResponse")]
    SessionService.Dominio.Enum.EnumEstadoInicioSesion IniciarSesion(LogicaDelNegocio.Modelo.CuentaModel Cuenta);
    
    [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/ISessionService/CerrarSesion", ReplyAction="http://tempuri.org/ISessionService/CerrarSesionResponse")]
    void CerrarSesion(LogicaDelNegocio.Modelo.CuentaModel Cuenta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISessionServiceCallback {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/EstaVivo", ReplyAction="http://tempuri.org/ISessionService/EstaVivoResponse")]
    bool EstaVivo();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISessionServiceChannel : ISessionService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SessionServiceClient : System.ServiceModel.DuplexClientBase<ISessionService>, ISessionService {
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress) {
    }
    
    public SessionService.Dominio.Enum.EnumEstadoInicioSesion IniciarSesion(LogicaDelNegocio.Modelo.CuentaModel Cuenta) {
        return base.Channel.IniciarSesion(Cuenta);
    }
    
    public void CerrarSesion(LogicaDelNegocio.Modelo.CuentaModel Cuenta) {
        base.Channel.CerrarSesion(Cuenta);
    }
}

namespace SessionService.Dominio.Enum
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EnumEstadoInicioSesion", Namespace = "http://schemas.datacontract.org/2004/07/SessionService.Dominio.Enum")]
    public enum EnumEstadoInicioSesion : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correcto = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CredencialesInvalidas = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CuentaNoVerificada = -1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorBD = -2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        CuentaYaLogeada = -3,
    }
}

