//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISessionService", CallbackContract=typeof(ISessionServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface ISessionService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/IniciarSesion", ReplyAction="http://tempuri.org/ISessionService/IniciarSesionResponse")]
    SessionService.Dominio.Enum.EnumEstadoInicioSesion IniciarSesion(LogicaDelNegocio.Modelo.CuentaModel cuenta);
    
    [System.ServiceModel.OperationContractAttribute(IsTerminating=true, Action="http://tempuri.org/ISessionService/CerrarSesion", ReplyAction="http://tempuri.org/ISessionService/CerrarSesionResponse")]
    void CerrarSesion(LogicaDelNegocio.Modelo.CuentaModel cuenta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISessionServiceCallback {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/EstaVivo", ReplyAction="http://tempuri.org/ISessionService/EstaVivoResponse")]
    bool EstaVivo();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ISessionServiceChannel : ISessionService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SessionServiceClient : System.ServiceModel.DuplexClientBase<ISessionService>, ISessionService {
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public SessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress) {
    }
    
    public SessionService.Dominio.Enum.EnumEstadoInicioSesion IniciarSesion(LogicaDelNegocio.Modelo.CuentaModel cuenta) {
        return base.Channel.IniciarSesion(cuenta);
    }
    
    public void CerrarSesion(LogicaDelNegocio.Modelo.CuentaModel cuenta) {
        base.Channel.CerrarSesion(cuenta);
    }
}
namespace LogicaDelNegocio.Modelo {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaModel", Namespace="http://schemas.datacontract.org/2004/07/LogicaDelNegocio.Modelo")]
    public partial class CuentaModel : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codigoVerificacionField;
        
        private string contrasenaField;
        
        private LogicaDelNegocio.Modelo.UsuarioModel informacionDeUsuarioField;
        
        private string nombreUsuarioField;
        
        private bool verificadoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigoVerificacion {
            get {
                return this.codigoVerificacionField;
            }
            set {
                this.codigoVerificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDelNegocio.Modelo.UsuarioModel informacionDeUsuario {
            get {
                return this.informacionDeUsuarioField;
            }
            set {
                this.informacionDeUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool verificado {
            get {
                return this.verificadoField;
            }
            set {
                this.verificadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioModel", Namespace="http://schemas.datacontract.org/2004/07/LogicaDelNegocio.Modelo")]
    public partial class UsuarioModel : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LogicaDelNegocio.Modelo.AvanceModel avanceDeUsuarioField;
        
        private string correoField;
        
        private string edadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDelNegocio.Modelo.AvanceModel avanceDeUsuario {
            get {
                return this.avanceDeUsuarioField;
            }
            set {
                this.avanceDeUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvanceModel", Namespace="http://schemas.datacontract.org/2004/07/LogicaDelNegocio.Modelo")]
    public partial class AvanceModel : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LogicaDelNegocio.Modelo.PersonajeCorredorModel[] corredoresAdquiridosField;
        
        private int mejorPuntuacionField;
        
        private int uvCoinsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDelNegocio.Modelo.PersonajeCorredorModel[] corredoresAdquiridos {
            get {
                return this.corredoresAdquiridosField;
            }
            set {
                this.corredoresAdquiridosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mejorPuntuacion {
            get {
                return this.mejorPuntuacionField;
            }
            set {
                this.mejorPuntuacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int uvCoins {
            get {
                return this.uvCoinsField;
            }
            set {
                this.uvCoinsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonajeCorredorModel", Namespace="http://schemas.datacontract.org/2004/07/LogicaDelNegocio.Modelo")]
    public partial class PersonajeCorredorModel : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nombreField;
        
        private string poderField;
        
        private int precioField;
        
        private double velocidadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poder {
            get {
                return this.poderField;
            }
            set {
                this.poderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double velocidad {
            get {
                return this.velocidadField;
            }
            set {
                this.velocidadField = value;
            }
        }
    }
}
namespace SessionService.Dominio.Enum {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumEstadoInicioSesion", Namespace="http://schemas.datacontract.org/2004/07/SessionService.Dominio.Enum")]
    public enum EnumEstadoInicioSesion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correcto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CredencialesInvalidas = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CuentaNoVerificada = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorBD = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CuentaYaLogeada = -3,
    }
}

