//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IGameService", CallbackContract=typeof(IGameServiceCallback))]
public interface IGameService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/UnirseASalaPrivada", ReplyAction="http://tempuri.org/IGameService/UnirseASalaPrivadaResponse")]
    GameService.Dominio.Enum.EnumEstadoDeUnirseASala UnirseASalaPrivada(string Id, LogicaDelNegocio.Modelo.CuentaModel Cuenta);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/UnirseASala", ReplyAction="http://tempuri.org/IGameService/UnirseASalaResponse")]
    bool UnirseASala(LogicaDelNegocio.Modelo.CuentaModel Cuenta);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/CrearSala", ReplyAction="http://tempuri.org/IGameService/CrearSalaResponse")]
    GameService.Dominio.Enum.EnumEstadoCrearSalaConId CrearSala(string Id, bool EsSalaPublica, LogicaDelNegocio.Modelo.CuentaModel Cuenta);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/VerificarSiEstoyEnSala", ReplyAction="http://tempuri.org/IGameService/VerificarSiEstoyEnSalaResponse")]
    bool VerificarSiEstoyEnSala(LogicaDelNegocio.Modelo.CuentaModel Cuenta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGameServiceCallback {
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/TerminarPartida")]
    void TerminarPartida();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SalaLlena")]
    void SalaLlena();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/NuevoCuentaEnLaSala")]
    void NuevoCuentaEnLaSala(LogicaDelNegocio.Modelo.CuentaModel cuenta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IGameServiceChannel : IGameService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GameServiceClient : System.ServiceModel.DuplexClientBase<IGameService>, IGameService {
    
    public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance) {
    }
    
    public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName) {
    }
    
    public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress) {
    }
    
    public GameService.Dominio.Enum.EnumEstadoDeUnirseASala UnirseASalaPrivada(string Id, LogicaDelNegocio.Modelo.CuentaModel Cuenta) {
        return base.Channel.UnirseASalaPrivada(Id, Cuenta);
    }
    
    public bool UnirseASala(LogicaDelNegocio.Modelo.CuentaModel Cuenta) {
        return base.Channel.UnirseASala(Cuenta);
    }
    
    public GameService.Dominio.Enum.EnumEstadoCrearSalaConId CrearSala(string Id, bool EsSalaPublica, LogicaDelNegocio.Modelo.CuentaModel Cuenta) {
        return base.Channel.CrearSala(Id, EsSalaPublica, Cuenta);
    }
    
    public bool VerificarSiEstoyEnSala(LogicaDelNegocio.Modelo.CuentaModel Cuenta) {
        return base.Channel.VerificarSiEstoyEnSala(Cuenta);
    }
}

namespace GameService.Dominio.Enum {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumEstadoDeUnirseASala", Namespace="http://schemas.datacontract.org/2004/07/GameService.Dominio.Enum")]
    public enum EnumEstadoDeUnirseASala : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnidoCorrectamente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalaInexistente = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalaLlena = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoSeEncuentraEnSesion = -2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumEstadoCrearSalaConId", Namespace="http://schemas.datacontract.org/2004/07/GameService.Dominio.Enum")]
    public enum EnumEstadoCrearSalaConId : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreadaCorrectamente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdYaExistente = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoSeEncuentraEnSesion = -2,
    }
}

