//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IChatService", CallbackContract=typeof(IChatServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IChatService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/Conectar", ReplyAction="http://tempuri.org/IChatService/ConectarResponse")]
    bool Conectar(LogicaDelNegocio.Modelo.CuentaModel cuenta);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/ObtenerCuentasConectadas", ReplyAction="http://tempuri.org/IChatService/ObtenerCuentasConectadasResponse")]
    LogicaDelNegocio.Modelo.CuentaModel[] ObtenerCuentasConectadas();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/EnviarMensaje")]
    void EnviarMensaje(GameChatService.Dominio.Message mensaje);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/EstaEscribiendo")]
    void EstaEscribiendo(string cuenta);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, IsTerminating=true, Action="http://tempuri.org/IChatService/Desconectar")]
    void Desconectar(LogicaDelNegocio.Modelo.CuentaModel cuenta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatServiceCallback {
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RefrescarCuentasConectadas")]
    void RefrescarCuentasConectadas(LogicaDelNegocio.Modelo.CuentaModel[] cuentasConectadas);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RecibirMensaje")]
    void RecibirMensaje(GameChatService.Dominio.Message mensaje);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/EstaEscribiendoCallback")]
    void EstaEscribiendoCallback(string cuenta);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Unirse")]
    void Unirse(LogicaDelNegocio.Modelo.CuentaModel cuenta);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Abandonar")]
    void Abandonar(LogicaDelNegocio.Modelo.CuentaModel cuenta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatServiceChannel : IChatService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<IChatService>, IChatService {
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance) {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName) {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress) {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress) {
    }
    
    public bool Conectar(LogicaDelNegocio.Modelo.CuentaModel cuenta) {
        return base.Channel.Conectar(cuenta);
    }
    
    public LogicaDelNegocio.Modelo.CuentaModel[] ObtenerCuentasConectadas() {
        return base.Channel.ObtenerCuentasConectadas();
    }
    
    public void EnviarMensaje(GameChatService.Dominio.Message mensaje) {
        base.Channel.EnviarMensaje(mensaje);
    }
    
    public void EstaEscribiendo(string cuenta) {
        base.Channel.EstaEscribiendo(cuenta);
    }
    
    public void Desconectar(LogicaDelNegocio.Modelo.CuentaModel cuenta) {
        base.Channel.Desconectar(cuenta);
    }
}
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonajeCorredorModel", Namespace="http://schemas.datacontract.org/2004/07/LogicaDelNegocio.Modelo")]
    public partial class PersonajeCorredorModel : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nombreField;
        
        private string poderField;
        
        private int precioField;
        
        private double velocidadField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poder {
            get {
                return this.poderField;
            }
            set {
                this.poderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double velocidad {
            get {
                return this.velocidadField;
            }
            set {
                this.velocidadField = value;
            }
        }
    }

namespace GameChatService.Dominio {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GameChatService.Dominio")]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime horaEnvioField;
        
        private string mensajeField;
        
        private LogicaDelNegocio.Modelo.CuentaModel remitenteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime horaEnvio {
            get {
                return this.horaEnvioField;
            }
            set {
                this.horaEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LogicaDelNegocio.Modelo.CuentaModel remitente {
            get {
                return this.remitenteField;
            }
            set {
                this.remitenteField = value;
            }
        }
    }
}

