//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICuentaService")]
public interface ICuentaService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaService/CheckIn", ReplyAction="http://tempuri.org/ICuentaService/CheckInResponse")]
    MessageService.Dominio.Enum.EnumEstadoRegistro CheckIn(LogicaDelNegocio.Modelo.CuentaModel newUser);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICuentaService/VerifyAccount", ReplyAction="http://tempuri.org/ICuentaService/VerifyAccountResponse")]
    MessageService.Dominio.Enum.EnumEstadoVerificarCuenta VerifyAccount(string code, LogicaDelNegocio.Modelo.CuentaModel cuenta);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICuentaServiceChannel : ICuentaService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CuentaServiceClient : System.ServiceModel.ClientBase<ICuentaService>, ICuentaService {
    
    public CuentaServiceClient() {
    }
    
    public CuentaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public CuentaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public CuentaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public CuentaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    public MessageService.Dominio.Enum.EnumEstadoRegistro CheckIn(LogicaDelNegocio.Modelo.CuentaModel newUser) {
        return base.Channel.CheckIn(newUser);
    }
    
    public MessageService.Dominio.Enum.EnumEstadoVerificarCuenta VerifyAccount(string code, LogicaDelNegocio.Modelo.CuentaModel cuenta) {
        return base.Channel.VerifyAccount(code, cuenta);
    }
}

namespace MessageService.Dominio.Enum {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumEstadoRegistro", Namespace="http://schemas.datacontract.org/2004/07/MessageService.Dominio.Enum")]
    public enum EnumEstadoRegistro : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegistroCorrecto = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsuarioExistente = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorEnBaseDatos = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumEstadoVerificarCuenta", Namespace="http://schemas.datacontract.org/2004/07/MessageService.Dominio.Enum")]
    public enum EnumEstadoVerificarCuenta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificadaCorrectamente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCoincideElCodigo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorEnBaseDatos = -1,
    }
}

